apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l8zdk8f0d-nodejs
  janus-idp.io/tekton: l8zdk8f0d-nodejs
  backstage.io/kubernetes-id: l8zdk8f0d-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l8zdk8f0d-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
